INSERT INTO `premier_league_stats`.`club` (`cod_club`, `club_name`, `wins`, `tie`, `defeats`) VALUES ('01', 'Arsenal', '16', '2', '1');
INSERT INTO `premier_league_stats`.`club` (`cod_club`, `club_name`, `wins`, `tie`, `defeats`) VALUES ('02', 'Aston Villa', '8', '4', '8');
INSERT INTO `premier_league_stats`.`club` (`cod_club`, `club_name`, `wins`, `tie`, `defeats`) VALUES ('03', 'Bournemouth', '4', '5', '11');
INSERT INTO `premier_league_stats`.`club` (`cod_club`, `club_name`, `wins`, `tie`, `defeats`) VALUES ('04', 'Brentford', '7', '9', '4');
INSERT INTO `premier_league_stats`.`club` (`cod_club`, `club_name`, `wins`, `tie`, `defeats`) VALUES ('05', 'Brighton', '9', '4', '6');
INSERT INTO `premier_league_stats`.`club` (`cod_club`, `club_name`, `wins`, `tie`, `defeats`) VALUES ('06', 'Chelsea', '8', '5', '7');
INSERT INTO `premier_league_stats`.`club` (`cod_club`, `club_name`, `wins`, `tie`, `defeats`) VALUES ('07', 'Crystal Palace', '6', '6', '8');
INSERT INTO `premier_league_stats`.`club` (`cod_club`, `club_name`, `wins`, `tie`, `defeats`) VALUES ('08', 'Everton', '3', '6', '11');
INSERT INTO `premier_league_stats`.`club` (`cod_club`, `club_name`, `wins`, `tie`, `defeats`) VALUES ('09', 'Fulham', '9', '4', '8');
INSERT INTO `premier_league_stats`.`club` (`cod_club`, `club_name`, `wins`, `tie`, `defeats`) VALUES ('10', 'Leeds United', '4', '6', '9');
INSERT INTO `premier_league_stats`.`club` (`cod_club`, `club_name`, `wins`, `tie`, `defeats`) VALUES ('11', 'Leicester City', '5', '3', '12');
INSERT INTO `premier_league_stats`.`club` (`cod_club`, `club_name`, `wins`, `tie`, `defeats`) VALUES ('12', 'Liverpool', '8', '5', '6');
INSERT INTO `premier_league_stats`.`club` (`cod_club`, `club_name`, `wins`, `tie`, `defeats`) VALUES ('13', 'Manchester City', '14', '3', '3');
INSERT INTO `premier_league_stats`.`club` (`cod_club`, `club_name`, `wins`, `tie`, `defeats`) VALUES ('14', 'Manchester United', '12', '3', '5');
INSERT INTO `premier_league_stats`.`club` (`cod_club`, `club_name`, `wins`, `tie`, `defeats`) VALUES ('15', 'Newcastle United', '10', '9', '1');
INSERT INTO `premier_league_stats`.`club` (`cod_club`, `club_name`, `wins`, `tie`, `defeats`) VALUES ('16', 'Nottingham Forest', '5', '6', '9');
INSERT INTO `premier_league_stats`.`club` (`cod_club`, `club_name`, `wins`, `tie`, `defeats`) VALUES ('17', 'Southampton', '4', '3', '13');
INSERT INTO `premier_league_stats`.`club` (`cod_club`, `club_name`, `wins`, `tie`, `defeats`) VALUES ('18', 'Tottenham', '11', '3', '7');
INSERT INTO `premier_league_stats`.`club` (`cod_club`, `club_name`, `wins`, `tie`, `defeats`) VALUES ('19', 'West ham', '5', '3', '12');
INSERT INTO `premier_league_stats`.`club` (`cod_club`, `club_name`, `wins`, `tie`, `defeats`) VALUES ('20', 'Wolves', '4', '5', '11');
