INSERT INTO `premier_league_stats`.`attack_stats` (`player_name`, `player_function`, `cod_club`, `goals`, `assists`) VALUES ('Erling Haaland', 'Forward', '13', '25', '3');
INSERT INTO `premier_league_stats`.`attack_stats` (`player_name`, `player_function`, `cod_club`, `goals`) VALUES ('Harry Kane', 'Forward', '18', '16');
INSERT INTO `premier_league_stats`.`attack_stats` (`player_name`, `player_function`, `cod_club`, `goals`) VALUES ('Ivan Toney', 'Forward', '4', '13');
INSERT INTO `premier_league_stats`.`attack_stats` (`player_name`, `player_function`, `cod_club`, `goals`) VALUES ('Aleksandar Mitrovic', 'Forward', '9', '11');
INSERT INTO `premier_league_stats`.`attack_stats` (`player_name`, `player_function`, `cod_club`, `goals`) VALUES ('Rodrigo', 'Forward', '10', '10');
INSERT INTO `premier_league_stats`.`attack_stats` (`player_name`, `player_function`, `cod_club`, `goals`) VALUES ('Miguel Almiron', 'Forward', '15', '9');
INSERT INTO `premier_league_stats`.`attack_stats` (`player_name`, `player_function`, `cod_club`, `goals`) VALUES ('Marcus Rashford', 'Midfielder', '14', '9');
INSERT INTO `premier_league_stats`.`attack_stats` (`player_name`, `player_function`, `cod_club`, `goals`) VALUES ('Martin Odegaard', 'Midfielder', '1', '8');
INSERT INTO `premier_league_stats`.`attack_stats` (`player_name`, `player_function`, `cod_club`, `goals`) VALUES ('James Maddison', 'Midfielder', '11', '7');
INSERT INTO `premier_league_stats`.`attack_stats` (`player_name`, `player_function`, `cod_club`, `goals`) VALUES ('Bukayo Saka', 'Midfielder', '1', '7');
INSERT INTO `premier_league_stats`.`attack_stats` (`player_name`, `player_function`, `cod_club`, `goals`) VALUES ('Roberto Firmino', 'Forward', '12', '7');
INSERT INTO `premier_league_stats`.`attack_stats` (`player_name`, `player_function`, `cod_club`, `goals`) VALUES ('Phil Foden', 'Forward', '13', '7');
INSERT INTO `premier_league_stats`.`attack_stats` (`player_name`, `player_function`, `cod_club`, `goals`) VALUES ('Gabriel Martinelli', 'Forward', '1', '7');
INSERT INTO `premier_league_stats`.`attack_stats` (`player_name`, `player_function`, `cod_club`, `goals`) VALUES ('Leandro Trossard', 'Forward', '1', '7');
INSERT INTO `premier_league_stats`.`attack_stats` (`player_name`, `player_function`, `cod_club`, `goals`) VALUES ('Mohamed Salah', 'Forward', '12', '7');
INSERT INTO `premier_league_stats`.`attack_stats` (`player_name`, `player_function`, `cod_club`, `goals`) VALUES ('Harvey Barnes', 'Midfielder', '11', '7');
INSERT INTO `premier_league_stats`.`attack_stats` (`player_name`, `player_function`, `cod_club`, `goals`) VALUES ('Pascal Grob', 'Midfielder', '5', '6');
INSERT INTO `premier_league_stats`.`attack_stats` (`player_name`, `player_function`, `cod_club`, `goals`) VALUES ('Callum Wilson', 'Forward', '15', '6');
INSERT INTO `premier_league_stats`.`attack_stats` (`player_name`, `player_function`, `cod_club`, `goals`) VALUES ('Danny Ings', 'Forward', '19', '6');
INSERT INTO `premier_league_stats`.`attack_stats` (`player_name`, `player_function`, `cod_club`, `goals`) VALUES ('Wilfried Zaha', 'Forward', '7', '6');
INSERT INTO `premier_league_stats`.`attack_stats` (`player_name`, `player_function`, `cod_club`, `goals`) VALUES ('James Ward-Prowse', 'Midfielder', '17', '5');
INSERT INTO `premier_league_stats`.`attack_stats` (`player_name`, `player_function`, `cod_club`, `goals`) VALUES ('Alexis Mac Allister', 'Midfielder', '5', '5');
INSERT INTO `premier_league_stats`.`attack_stats` (`player_name`, `player_function`, `cod_club`, `goals`) VALUES ('Gabriel Jesus', 'Forward', '1', '5');
INSERT INTO `premier_league_stats`.`attack_stats` (`player_name`, `player_function`, `cod_club`, `goals`) VALUES ('Darwin Nunez', 'Forward', '12', '5');
INSERT INTO `premier_league_stats`.`attack_stats` (`player_name`, `player_function`, `cod_club`, `goals`) VALUES ('Kai Havertz', 'Forward', '6', '5');
INSERT INTO `premier_league_stats`.`attack_stats` (`player_name`, `player_function`, `cod_club`, `goals`) VALUES ('Daniel Podence', 'Forward', '20', '5');
INSERT INTO `premier_league_stats`.`attack_stats` (`player_name`, `player_function`, `cod_club`, `goals`) VALUES ('Bruno Fernandes', 'Midfielder', '14', '4');
INSERT INTO `premier_league_stats`.`attack_stats` (`player_name`, `player_function`, `cod_club`, `goals`) VALUES ('Riyad Mahrez', 'Forward', '13', '4');
INSERT INTO `premier_league_stats`.`attack_stats` (`player_name`, `player_function`, `cod_club`, `goals`) VALUES ('Pierre-Emile', 'Midfielder', '18', '4');
INSERT INTO `premier_league_stats`.`attack_stats` (`player_name`, `player_function`, `cod_club`, `goals`) VALUES ('Ruben Neves', 'Midfielder', '20', '4');
INSERT INTO `premier_league_stats`.`attack_stats` (`player_name`, `player_function`, `cod_club`, `goals`) VALUES ('Rodrigo Bentancur', 'Midfielder', '18', '4');
INSERT INTO `premier_league_stats`.`attack_stats` (`player_name`, `player_function`, `cod_club`, `goals`) VALUES ('Solly March', 'Midfielder', '5', '4');
INSERT INTO `premier_league_stats`.`attack_stats` (`player_name`, `player_function`, `cod_club`, `goals`) VALUES ('Heung-min Son', 'Forward', '18', '4');
INSERT INTO `premier_league_stats`.`attack_stats` (`player_name`, `player_function`, `cod_club`, `goals`) VALUES ('Kaoru Mitoma', 'Midfielder', '5', '4');
INSERT INTO `premier_league_stats`.`attack_stats` (`player_name`, `player_function`, `cod_club`, `goals`) VALUES ('Bryan Mbeumo', 'Forward', '4', '4');
INSERT INTO `premier_league_stats`.`attack_stats` (`player_name`, `player_function`, `cod_club`, `goals`) VALUES ('Jarrod Bowen', 'Midfielder', '19', '4');
INSERT INTO `premier_league_stats`.`attack_stats` (`player_name`, `player_function`, `cod_club`, `goals`) VALUES ('Philip Billing', 'Midfielder', '3', '4');
INSERT INTO `premier_league_stats`.`attack_stats` (`player_name`, `player_function`, `cod_club`, `goals`) VALUES ('Che Adams', 'Forward', '17', '4');
INSERT INTO `premier_league_stats`.`attack_stats` (`player_name`, `player_function`, `cod_club`, `goals`) VALUES ('Julian Alvarez', 'Forward', '13', '4');
INSERT INTO `premier_league_stats`.`attack_stats` (`player_name`, `player_function`, `cod_club`, `goals`) VALUES ('Yoane Wissa', 'Forward', '4', '4');
INSERT INTO `premier_league_stats`.`attack_stats` (`player_name`, `player_function`, `cod_club`, `goals`) VALUES ('Brennan Johnson', 'Forward', '16', '4');
INSERT INTO `premier_league_stats`.`attack_stats` (`player_name`, `player_function`, `cod_club`, `goals`) VALUES ('Raheem Sterling', 'Forward', '6', '4');
INSERT INTO `premier_league_stats`.`attack_stats` (`player_name`, `player_function`, `cod_club`, `goals`) VALUES ('Edward Nketiah', 'Forward', '1', '4');
INSERT INTO `premier_league_stats`.`attack_stats` (`player_name`, `player_function`, `cod_club`, `goals`) VALUES ('Kieffer Moore', 'Forward', '3', '4');
INSERT INTO `premier_league_stats`.`attack_stats` (`player_name`, `player_function`, `cod_club`, `goals`) VALUES ('Bobby Decordova-Reid', 'Midfielder', '9', '4');
INSERT INTO `premier_league_stats`.`attack_stats` (`player_name`, `player_function`, `cod_club`, `goals`) VALUES ('Leon Bailey', 'Forward', '2', '4');
INSERT INTO `premier_league_stats`.`attack_stats` (`player_name`, `player_function`, `cod_club`, `goals`) VALUES ('Ollie Watkins', 'Forward', '2', '4');
INSERT INTO `premier_league_stats`.`attack_stats` (`player_name`, `player_function`, `cod_club`, `goals`) VALUES ('Crysencio Summerville', 'Forward', '10', '4');
INSERT INTO `premier_league_stats`.`attack_stats` (`player_name`, `player_function`, `cod_club`, `goals`) VALUES ('Taiwo Awoniyi', 'Forward', '16', '4');
INSERT INTO `premier_league_stats`.`attack_stats` (`player_name`, `player_function`, `cod_club`, `goals`) VALUES ('Kevin De Bruyne', 'Midfielder', '13', '3');


